research_task:
  description: >
    Coletar e resumir artigos de notícias recentes, imprensa
    lançamentos e análises de mercado relacionadas ao estoque e
    sua indústria de criptomoedas e blockchain
    Preste atenção especial a quaisquer eventos significativos,
    sentimentos e opiniões dos analistas em cripmoedas. Incluir também os próximos 
    eventos como ganhos.
    
        
  expected_output: >
    Sua resposta final DEVE ser um relatório que inclua uma
    resumo abrangente das últimas notícias, qualquer notável
    mudanças no sentimento do mercado e impactos potenciais sobre o cenário atual de cripmoedas


reporting_task:
  description: >
    Faça uma análise completa da situação financeira das cripmoedas
    desempenho do mercado atual. 
    Isso inclui examinar as principais métricas financeiras de cripmoedas, como métricas on-chain, rsi, macd, volume, entre outras.        Além disso, analise o desempenho da criptomoeda em comparação 
    aos seus pares da indústria e às tendências gerais do mercado.
  expected_output: >
    Seu relatório final DEVE expandir o resumo fornecido
    mas agora incluindo uma avaliação clara da situação
    situação financeira, seus pontos fortes e fracos, do cenário atual de criptomoedas
    Relatórios completos com os principais tópicos, cada um com uma seção completa de informações.
    Formatado como markdown sem '```'


translate_task:
  description: >
    Translate the information to Brazilian Portuguese
  expected_output: >
    A fully translated report in Brazilian Portuguese
    Formated as markdown with out '```'